### ISSUE TITLE
Wrong language

### ISSUE THREAD

**Issue by yumedia** [KyranRana/cloudflare-bypass#16]
UTF-8 not show correctly.

**Comment by KyranRana** [comment]
Hi there. Sorry is this still a problem for you?

**Comment by yumedia** [comment]
Yes, it still problem but I don't see any reply :(

**Comment by KyranRana** [comment]
I will fix it, I am just busy as its the christmas period. I am sorry. Give me 3 days and it will be looked into and possibly fixed. Please re-open the issue with the appropriate info :)

**Comment by yumedia** [comment]
I re-opened it mate !

**Comment by KyranRana** [comment]
This has been fixed in the latest commit, let me know if this sorts out your problem.

Just applied a hot fix for now. I will be doing some major updates to the script to make it more flexible in the next week or so.  I will make it so any of the standard requesting components can be plugged in (file_get_contents / custom cURL handles).

**Comment by yumedia** [comment]
Thank you !
