### ISSUE TITLE
Missing library in Packagist

### ISSUE THREAD

**Issue by railken** [KyranRana/cloudflare-bypass#35]
This library is missing in Packagist, so it can't be installed using composer

**Comment by KyranRana** [comment]
Yea, since V2 is experimental I am going to let it ride for a bit of time.

I still need to add some form of testing for making sure the library works, but haven't got time to do it just yet. Once this has been done and V2 is proved stable, I will make my first release and add the github repo to packagist. 

Have you managed to test the library yet? And if so does it work for the site you plan on using it on?

**Comment by railken** [comment]
Yup it works pretty well.

I made a fork and added some tests with phpunit.
Tested guzzlehttp with the site of my interest and it works

**Comment by KyranRana** [comment]
Package is now available on composer:

https://packagist.org/packages/kyranrana/cloudflare-bypass
